# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('ip_address', models.CharField(default='11', max_length=200)),
                ('port_number', models.CharField(default='6000', max_length=10)),
                ('file_directory', models.CharField(default='/Users/Username/Desktop ', max_length=1000)),
                ('friends', models.ManyToManyField(blank=True, default=None, related_name='_user_friends_+', to='fileTransfer.User')),
            ],
        ),
    ]
