# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileTransfer', '0002_transfer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='port_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=models.CharField(default='127.0.0.1', max_length=200),
        ),
    ]
