# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date made')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='password',
            name='user',
        ),
        migrations.DeleteModel(
            name='PassWord',
        ),
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
