# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160401_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
    ]
