# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20160415_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(blank=True, default=None, related_name='_user_friend_+', to='login.User'),
        ),
    ]
