# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20160415_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
