# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20160415_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_directory',
            field=models.CharField(default='/Users/Username/Desktop ', max_length=1000),
        ),
    ]
