# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20160415_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_date',
        ),
    ]
